coverage:
  precision: 2
  round: down
  range: 40..100
  status:
    project:
      default:
        # Require overall coverage to stay above this target
        target: 70%
        # Allow small fluctuations without failing status
        threshold: 2%
        informational: false
    patch:
      default:
        # Auto target relative to project coverage; do not block PRs
        target: auto
        threshold: 2%
        informational: true

# Ignore non-source paths and generated code
ignore:
  - android/**
  - ios/**
  - linux/**
  - macos/**
  - windows/**
  - web/**
  - test/**
  - packages/**/test/**
  - "**/*.g.dart"

comment:
  layout: reach, diff, flags, files
  behavior: default
  require_changes: true
  require_head: true

github_checks:
  annotations: true

