name: domain
description: Domain layer for flutter_task_manager
version: 0.1.0
publish_to: 'none'

environment:
  sdk: ^3.8.1

dependencies:
  equatable: ^2.0.5

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
